# Generated by Django 5.1.1 on 2024-09-26 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddProperty', '0002_remove_listing_open_house_alter_listing_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='list_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='developer',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='publishe_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
