# Generated by Django 5.1.1 on 2024-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('news_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.URLField(max_length=500)),
            ],
        ),
    ]
